version: '3'

services:
  zulip-botserver:
    build: .
    ports:
      - "5002:5002"
    volumes:
      - ./botserverrc:/app/botserverrc
    restart: unless-stopped
    command: zulip-botserver -c botserverrc
